# tools/schemaep/traductions.py
"""Traductions du catalogue SchemAEP : français → (en, es, pt, de).

Le catalogue est rédigé en français et le reste en interne : valeurs des
fichiers .json, défauts validés, parité avec la page SchemAEP. Ces textes
servent à l'affichage seulement (voir langue.traduire) : un texte entier
(nom de pièce, champ, option) y est cherché tel quel ; une phrase composée
(ligne de nomenclature, étiquette, message de contrôle) est traduite morceau
par morceau, le plus long d'abord. La casse de l'initiale suit celle du texte
français (« Bride » / « bride »).
"""

CATALOGUE = {
    # ── Matériaux ───────────────────────────────────────────────────────
    'Fonte ductile': ('Ductile iron', 'Fundición dúctil', 'Ferro fundido dúctil', 'Duktilguss'),
    'PVC pression': ('Pressure PVC', 'PVC presión', 'PVC pressão', 'Druck-PVC'),
    'PEHD': ('HDPE', 'PEAD', 'PEAD', 'PE-HD'),
    'Laiton / acier fileté': ('Threaded brass / steel', 'Latón / acero roscado', 'Latão / aço roscado',
                              'Messing / Stahl mit Gewinde'),
    'fonte': ('ductile iron', 'fundición', 'ferro fundido', 'Guss'),
    'laiton': ('brass', 'latón', 'latão', 'Messing'),

    # ── Extrémités ──────────────────────────────────────────────────────
    'emboîtement': ('socket', 'enchufe', 'boca', 'Muffe'),
    'emboîtement Express': ('Express socket', 'enchufe Express', 'boca Express', 'Express-Muffe'),
    'emboîtement verrouillé': ('restrained socket', 'enchufe acerrojado', 'boca travada',
                               'längskraftschlüssige Muffe'),
    'bout uni': ('spigot', 'extremo liso', 'ponta lisa', 'Spitzende'),
    'bride': ('flange', 'brida', 'flange', 'Flansch'),
    'brides': ('flanges', 'bridas', 'flanges', 'Flansche'),
    'électrosoudable': ('electrofusion', 'electrosoldable', 'eletrossoldável', 'Elektroschweiß'),
    'raccord à compression': ('compression fitting', 'racor de compresión', 'união de compressão',
                              'Klemmverbinder'),
    'filetage femelle': ('female thread', 'rosca hembra', 'rosca fêmea', 'Innengewinde'),
    'filetage mâle': ('male thread', 'rosca macho', 'rosca macho', 'Außengewinde'),
    'universel (tout bout uni)': ('universal (any spigot)', 'universal (cualquier extremo liso)',
                                  'universal (qualquer ponta lisa)', 'universal (jedes Spitzende)'),
    'sur conduite / libre': ('on pipe / free', 'sobre tubería / libre', 'sobre conduta / livre',
                             'auf Leitung / frei'),

    # ── Suggestions d'assemblage ────────────────────────────────────────
    'bride-emboîtement (BE) ou adaptateur de bride multi-matériaux': (
        'flange-socket (BE) or multi-material flange adaptor',
        'brida-enchufe (BE) o adaptador de brida multimaterial',
        'flange-boca (BE) ou adaptador de flange multimaterial',
        'Flansch-Muffen-Stück (BE) oder Mehrwerkstoff-Flanschadapter'),
    'bout uni manquant : tronçon de tuyau ou pièce à bout uni': (
        'missing spigot: pipe section or spigot fitting',
        'falta extremo liso: tramo de tubo o pieza con extremo liso',
        'falta ponta lisa: troço de tubo ou peça com ponta lisa',
        'Spitzende fehlt: Rohrstück oder Formstück mit Spitzende'),
    'tronçon de tuyau PE entre les deux raccords': (
        'PE pipe section between the two fittings', 'tramo de tubo PE entre los dos racores',
        'troço de tubo PE entre as duas uniões', 'PE-Rohrstück zwischen den beiden Verbindern'),
    'tronçon de tuyau PE': ('PE pipe section', 'tramo de tubo PE', 'troço de tubo PE', 'PE-Rohrstück'),
    'tronçon de tuyau': ('pipe section', 'tramo de tubo', 'troço de tubo', 'Rohrstück'),
    'manchon ou raccord universel': ('coupling or universal fitting', 'manguito o racor universal',
                                     'manga ou união universal', 'Muffe oder Universalverbinder'),
    'bride taraudée': ('threaded flange', 'brida roscada', 'flange roscada', 'Gewindeflansch'),
    'tronçon PE + raccord compression femelle': (
        'PE section + female compression fitting', 'tramo PE + racor de compresión hembra',
        'troço PE + união de compressão fêmea', 'PE-Stück + Klemmverbinder mit Innengewinde'),
    'tronçon PE + raccord compression mâle': (
        'PE section + male compression fitting', 'tramo PE + racor de compresión macho',
        'troço PE + união de compressão macho', 'PE-Stück + Klemmverbinder mit Außengewinde'),
    'tronçon PE + adaptateur': ('PE section + adaptor', 'tramo PE + adaptador', 'troço PE + adaptador',
                                'PE-Stück + Adapter'),
    'pièce d’adaptation à prévoir': ('adaptor fitting required', 'prever pieza de adaptación',
                                     'prever peça de adaptação', 'Übergangsstück vorsehen'),

    # ── Familles ────────────────────────────────────────────────────────
    'Canalisations': ('Pipes', 'Tuberías', 'Condutas', 'Leitungen'),
    'Raccords réseau': ('Network fittings', 'Accesorios de red', 'Acessórios de rede', 'Netzformstücke'),
    'Raccords PE & filetés': ('PE & threaded fittings', 'Accesorios PE y roscados',
                              'Acessórios PE e roscados', 'PE- und Gewindeformstücke'),
    'Robinetterie': ('Valves', 'Valvulería', 'Válvulas', 'Armaturen'),
    'Régulation & protection': ('Control & protection', 'Regulación y protección', 'Regulação e proteção',
                                'Regelung & Schutz'),
    'Branchement & comptage': ('Service connection & metering', 'Acometida y medición', 'Ramal e contagem',
                               'Hausanschluss & Messung'),
    'Incendie & usages': ('Fire & other uses', 'Incendios y usos', 'Incêndio e usos', 'Brandschutz & Nutzung'),
    'Ouvrages': ('Structures', 'Obras', 'Obras', 'Bauwerke'),
    'Annotations': ('Annotations', 'Anotaciones', 'Anotações', 'Anmerkungen'),

    # ── Champs ──────────────────────────────────────────────────────────
    'Matériau': ('Material', 'Material', 'Material', 'Werkstoff'),
    'Diamètre': ('Diameter', 'Diámetro', 'Diâmetro', 'Durchmesser'),
    'Diamètre PE': ('PE diameter', 'Diámetro PE', 'Diâmetro PE', 'PE-Durchmesser'),
    'Diamètre (filetage)': ('Diameter (thread)', 'Diámetro (rosca)', 'Diâmetro (rosca)', 'Durchmesser (Gewinde)'),
    'Diamètre tubulure': ('Branch diameter', 'Diámetro de derivación', 'Diâmetro da derivação',
                          'Abgangsdurchmesser'),
    'Diamètre dérivations': ('Branches diameter', 'Diámetro de derivaciones', 'Diâmetro das derivações',
                             'Abgangsdurchmesser'),
    'Diamètre réduit': ('Reduced diameter', 'Diámetro reducido', 'Diâmetro reduzido', 'Reduzierter Durchmesser'),
    'Diamètre départ': ('Outlet diameter', 'Diámetro de salida', 'Diâmetro de saída', 'Abgangsdurchmesser'),
    'Diamètre arrivée / vidange': ('Inlet / drain diameter', 'Diámetro de entrada / vaciado',
                                   'Diâmetro de entrada / descarga', 'Zulauf-/Entleerungsdurchmesser'),
    'Grand diamètre': ('Large diameter', 'Diámetro mayor', 'Diâmetro maior', 'Großer Durchmesser'),
    'Petit diamètre': ('Small diameter', 'Diámetro menor', 'Diâmetro menor', 'Kleiner Durchmesser'),
    'Massif de butée béton': ('Concrete thrust block', 'Macizo de anclaje de hormigón',
                              'Maciço de amarração em betão', 'Betonwiderlager'),
    'Joints verrouillés': ('Restrained joints', 'Juntas acerrojadas', 'Juntas travadas',
                           'Längskraftschlüssige Verbindungen'),
    'Bouche à clé + tige': ('Valve box + stem', 'Arqueta de llave + vástago', 'Caixa de manobra + haste',
                            'Straßenkappe + Einbaugarnitur'),
    'Sous regard / chambre': ('In chamber', 'Bajo arqueta / cámara', 'Em caixa / câmara',
                              'Im Schacht / in der Kammer'),
    'Extrémités': ('Ends', 'Extremos', 'Extremidades', 'Enden'),
    'Longueur réelle (m)': ('Actual length (m)', 'Longitud real (m)', 'Comprimento real (m)',
                            'Tatsächliche Länge (m)'),
    'Longueur dessin (0 = auto)': ('Drawn length (0 = auto)', 'Longitud de dibujo (0 = auto)',
                                   'Comprimento no desenho (0 = auto)', 'Zeichenlänge (0 = auto)'),
    'Longueur (m)': ('Length (m)', 'Longitud (m)', 'Comprimento (m)', 'Länge (m)'),
    'Grillage avertisseur': ('Warning mesh', 'Malla de señalización', 'Rede de sinalização', 'Trassenwarnband'),
    'Sous fourreau': ('In sleeve', 'En funda', 'Em manga', 'Im Schutzrohr'),
    'Angle': ('Angle', 'Ángulo', 'Ângulo', 'Winkel'),
    'Type': ('Type', 'Tipo', 'Tipo', 'Typ'),
    'Standard': ('Standard', 'Estándar', 'Padrão', 'Standard'),
    'D’ancrage et d’étanchéité': ('Anchoring and sealing', 'De anclaje y estanqueidad',
                                  'De ancoragem e estanquidade', 'Anker- und Dichtausführung'),
    'Sortie (réduit si <)': ('Outlet (reduced if <)', 'Salida (reducida si <)', 'Saída (reduzida se <)',
                             'Abgang (reduziert wenn <)'),
    'Dérivation': ('Branch', 'Derivación', 'Derivação', 'Abgang'),
    'Mâle': ('Male', 'Macho', 'Macho', 'Außengewinde'),
    'Femelle': ('Female', 'Hembra', 'Fêmea', 'Innengewinde'),
    'Manœuvre': ('Operation', 'Maniobra', 'Manobra', 'Betätigung'),
    'Filetages': ('Threads', 'Roscas', 'Roscas', 'Gewinde'),
    'Repère': ('Tag', 'Referencia', 'Referência', 'Kennung'),
    'Consigne aval (bar)': ('Downstream setpoint (bar)', 'Consigna aguas abajo (bar)',
                            'Consigna a jusante (bar)', 'Ausgangsdruck-Sollwert (bar)'),
    'Consigne amont (bar)': ('Upstream setpoint (bar)', 'Consigna aguas arriba (bar)',
                             'Consigna a montante (bar)', 'Eingangsdruck-Sollwert (bar)'),
    'Débit (m³/h)': ('Flow (m³/h)', 'Caudal (m³/h)', 'Caudal (m³/h)', 'Durchfluss (m³/h)'),
    'Fonction(s)': ('Function(s)', 'Función(es)', 'Função(ões)', 'Funktion(en)'),
    'Robinet d’isolement': ('Isolating valve', 'Válvula de aislamiento', 'Válvula de isolamento',
                            'Absperrventil'),
    'Rejet': ('Discharge', 'Vertido', 'Descarga', 'Ableitung'),
    'Tarage (bar)': ('Set pressure (bar)', 'Tarado (bar)', 'Calibração (bar)', 'Ansprechdruck (bar)'),
    'Volume (L)': ('Volume (L)', 'Volumen (L)', 'Volume (L)', 'Volumen (L)'),
    'Volume (m³)': ('Volume (m³)', 'Volumen (m³)', 'Volume (m³)', 'Volumen (m³)'),
    'Conduite principale': ('Main pipe', 'Tubería principal', 'Conduta principal', 'Hauptleitung'),
    'Branchement PE': ('PE service pipe', 'Acometida PE', 'Ramal PE', 'PE-Anschlussleitung'),
    'Usage': ('Use', 'Uso', 'Utilização', 'Verwendung'),
    'Technologie': ('Technology', 'Tecnología', 'Tecnologia', 'Technologie'),
    'Logement': ('Housing', 'Alojamiento', 'Alojamento', 'Einbauort'),
    'Tête émettrice (télérelève)': ('Transmitter (remote reading)', 'Emisor (telelectura)',
                                    'Emissor (telecontagem)', 'Funkmodul (Fernauslesung)'),
    'Nom / n°': ('Name / no.', 'Nombre / n.º', 'Nome / n.º', 'Name / Nr.'),
    'Repère / rue': ('Tag / street', 'Referencia / calle', 'Referência / rua', 'Kennung / Straße'),
    'Cote point géodésique (m)': ('Survey point level (m)', 'Cota del punto geodésico (m)',
                                  'Cota do ponto geodésico (m)', 'Höhe Festpunkt (m)'),
    'HMT (m)': ('TDH (m)', 'AMT (m)', 'AMT (m)', 'Förderhöhe (m)'),
    'Nombre': ('Number', 'Número', 'Número', 'Anzahl'),
    'Profondeur (m)': ('Depth (m)', 'Profundidad (m)', 'Profundidade (m)', 'Tiefe (m)'),
    'Libellé': ('Label', 'Rótulo', 'Rótulo', 'Bezeichnung'),
    'Dimensions réelles': ('Actual dimensions', 'Dimensiones reales', 'Dimensões reais',
                           'Tatsächliche Abmessungen'),
    'Largeur dessin': ('Drawn width', 'Ancho de dibujo', 'Largura no desenho', 'Zeichenbreite'),
    'Hauteur dessin': ('Drawn height', 'Alto de dibujo', 'Altura no desenho', 'Zeichenhöhe'),
    'Compter en nomenclature': ('Count in bill of materials', 'Contar en la lista de materiales',
                                'Contar na lista de materiais', 'In Stückliste zählen'),
    'Texte': ('Text', 'Texto', 'Texto', 'Text'),
    'Taille': ('Size', 'Tamaño', 'Tamanho', 'Größe'),

    # ── Options ─────────────────────────────────────────────────────────
    'Emboîtement + bout uni': ('Socket + spigot', 'Enchufe + extremo liso', 'Boca + ponta lisa',
                               'Muffe + Spitzende'),
    'Express + bout uni': ('Express + spigot', 'Express + extremo liso', 'Express + ponta lisa',
                           'Express + Spitzende'),
    'Tuyau à brides': ('Flanged pipe', 'Tubo con bridas', 'Tubo flangeado', 'Flanschrohr'),
    'Bouts unis (coupe)': ('Plain ends (cut)', 'Extremos lisos (corte)', 'Pontas lisas (corte)',
                           'Spitzenden (Schnitt)'),
    'Bouts unis (soudage / raccords)': ('Plain ends (welding / fittings)', 'Extremos lisos (soldadura / racores)',
                                        'Pontas lisas (soldadura / uniões)', 'Spitzenden (Schweißen / Verbinder)'),
    '2 emboîtements': ('2 sockets', '2 enchufes', '2 bocas', '2 Muffen'),
    '2 emboîtements + tubulure à bride': ('2 sockets + flanged branch', '2 enchufes + derivación con brida',
                                          '2 bocas + derivação flangeada', '2 Muffen + Flanschabgang'),
    '3 emboîtements': ('3 sockets', '3 enchufes', '3 bocas', '3 Muffen'),
    '2 brides': ('2 flanges', '2 bridas', '2 flanges', '2 Flansche'),
    '3 brides': ('3 flanges', '3 bridas', '3 flanges', '3 Flansche'),
    '2 bouts unis': ('2 spigots', '2 extremos lisos', '2 pontas lisas', '2 Spitzenden'),
    'à souder bout à bout': ('butt-welded', 'para soldar a tope', 'para soldar topo a topo', 'stumpfgeschweißt'),
    'Bouchon (sur bout uni)': ('Cap (on spigot)', 'Tapón (sobre extremo liso)', 'Tampão (sobre ponta lisa)',
                               'Kappe (auf Spitzende)'),
    'Obturateur (dans emboîtement)': ('Plug (in socket)', 'Obturador (en enchufe)', 'Obturador (na boca)',
                                      'Stopfen (in Muffe)'),
    'Bouchon électrosoudable': ('Electrofusion cap', 'Tapón electrosoldable', 'Tampão eletrossoldável',
                                'Elektroschweiß-Kappe'),
    'Bouchon à souder': ('Butt-weld cap', 'Tapón para soldar', 'Tampão para soldar', 'Schweißkappe'),
    'Manchon simple': ('Plain coupling', 'Manguito simple', 'Manga simples', 'Einfache Muffe'),
    'Manchon coulissant (réparation)': ('Sliding coupling (repair)', 'Manguito deslizante (reparación)',
                                        'Manga deslizante (reparação)', 'Überschiebmuffe (Reparatur)'),
    'Manchon coulissant': ('Sliding coupling', 'Manguito deslizante', 'Manga deslizante', 'Überschiebmuffe'),
    'Auto-buté (verrouillé)': ('Self-restrained (locked)', 'Autoblocante (acerrojado)',
                               'Autotravado (travado)', 'Selbstsichernd (längskraftschlüssig)'),
    'Joint de démontage auto-buté': ('Self-restrained dismantling joint', 'Carrete de desmontaje autoblocante',
                                     'Junta de desmontagem autotravada', 'Selbstsicherndes Ausbaustück'),
    'Joint de démontage': ('Dismantling joint', 'Carrete de desmontaje', 'Junta de desmontagem', 'Ausbaustück'),
    'Collier de réparation grande largeur': ('Wide repair clamp', 'Abrazadera de reparación ancha',
                                             'Braçadeira de reparação larga', 'Breite Reparaturschelle'),
    'Collier de réparation': ('Repair clamp', 'Abrazadera de reparación', 'Braçadeira de reparação',
                              'Reparaturschelle'),
    'Grande largeur': ('Wide', 'Ancha', 'Larga', 'Breit'),
    'Carré (bouche à clé)': ('Square (valve box)', 'Cuadradillo (arqueta de llave)', 'Quadra (caixa de manobra)',
                             'Vierkant (Straßenkappe)'),
    'Carré de manœuvre': ('Operating square', 'Cuadradillo de maniobra', 'Quadra de manobra', 'Bedienvierkant'),
    'Volant': ('Handwheel', 'Volante', 'Volante', 'Handrad'),
    'Réducteur à volant': ('Gearbox with handwheel', 'Reductor con volante', 'Redutor com volante',
                           'Getriebe mit Handrad'),
    'Réducteur': ('Gearbox', 'Reductor', 'Redutor', 'Getriebe'),
    'Motorisée (actionneur)': ('Motorised (actuator)', 'Motorizada (actuador)', 'Motorizada (atuador)',
                               'Motorisch (Stellantrieb)'),
    'Motorisée': ('Motorised', 'Motorizada', 'Motorizada', 'Motorisch'),
    'Levier': ('Lever', 'Palanca', 'Alavanca', 'Hebel'),
    'à brides': ('flanged', 'con bridas', 'flangeado', 'mit Flanschen'),
    'à emboîtements': ('socketed', 'con enchufes', 'com bocas', 'mit Muffen'),
    'bride + emboîtement': ('flange + socket', 'brida + enchufe', 'flange + boca', 'Flansch + Muffe'),
    'femelle / femelle': ('female / female', 'hembra / hembra', 'fêmea / fêmea', 'Innen / Innen'),
    'mâle / femelle': ('male / female', 'macho / hembra', 'macho / fêmea', 'Außen / Innen'),
    'mâle / mâle': ('male / male', 'macho / macho', 'macho / macho', 'Außen / Außen'),
    'À battant': ('Swing', 'De clapeta', 'De batente', 'Klappe'),
    'Double battant': ('Dual plate', 'Doble clapeta', 'Duplo batente', 'Doppelklappe'),
    'À boule': ('Ball', 'De bola', 'De esfera', 'Kugel'),
    'À ressort': ('Spring', 'De resorte', 'De mola', 'Feder'),
    'Trifonctionnelle': ('Triple-function', 'Trifuncional', 'Trifuncional', 'Dreifachfunktion'),
    'Double fonction': ('Double-function', 'Doble función', 'Dupla função', 'Doppelfunktion'),
    'Simple fonction (dégazage)': ('Single-function (air release)', 'Función simple (purga de aire)',
                                   'Função simples (desgaseificação)', 'Einfachfunktion (Entlüftung)'),
    'Simple fonction': ('Single-function', 'Función simple', 'Função simples', 'Einfachfunktion'),
    'Fossé / exutoire naturel': ('Ditch / natural outfall', 'Cuneta / desagüe natural',
                                 'Vala / descarga natural', 'Graben / natürlicher Vorfluter'),
    'Fossé / exutoire': ('Ditch / outfall', 'Cuneta / desagüe', 'Vala / descarga', 'Graben / Vorfluter'),
    'Regard de vidange (pompage)': ('Drain chamber (pumping)', 'Arqueta de vaciado (bombeo)',
                                    'Caixa de descarga (bombagem)', 'Entleerungsschacht (Pumpen)'),
    'Regard de vidange': ('Drain chamber', 'Arqueta de vaciado', 'Caixa de descarga', 'Entleerungsschacht'),
    'Réseau d’eaux pluviales': ('Stormwater network', 'Red de pluviales', 'Rede de águas pluviais',
                                'Regenwassernetz'),
    'Réseau pluvial': ('Stormwater network', 'Red pluvial', 'Rede pluvial', 'Regenwassernetz'),
    'Réseau d’eaux usées': ('Foul water network', 'Red de aguas residuales', 'Rede de águas residuais',
                            'Schmutzwassernetz'),
    'Réservoir à vessie': ('Bladder vessel', 'Calderín de vejiga', 'Reservatório de membrana', 'Blasenspeicher'),
    'À vessie': ('Bladder', 'De vejiga', 'De membrana', 'Blasenspeicher'),
    'Réservoir à air': ('Air vessel', 'Calderín de aire', 'Reservatório de ar', 'Luftspeicher'),
    'À air (compresseur)': ('Air (compressor)', 'De aire (compresor)', 'De ar (compressor)', 'Luft (Kompressor)'),
    'Cheminée d’équilibre': ('Surge tower', 'Chimenea de equilibrio', 'Chaminé de equilíbrio', 'Wasserschloss'),
    'Collier + robinet (2 pièces)': ('Clamp + valve (2 parts)', 'Collarín + llave (2 piezas)',
                                     'Braçadeira + válvula (2 peças)', 'Schelle + Ventil (2 Teile)'),
    'Collier + robinet': ('Clamp + valve', 'Collarín + llave', 'Braçadeira + válvula', 'Schelle + Ventil'),
    'Robinet à collier intégré': ('Valve with integrated clamp', 'Llave con collarín integrado',
                                  'Válvula com braçadeira integrada', 'Ventil mit integrierter Schelle'),
    'Prise électrosoudable PE (avec robinet)': ('PE electrofusion tapping tee (with valve)',
                                                'Toma electrosoldable PE (con llave)',
                                                'Tomada eletrossoldável PE (com válvula)',
                                                'PE-Elektroschweiß-Anbohrarmatur (mit Ventil)'),
    'Prise électrosoudable PE': ('PE electrofusion tapping tee', 'Toma electrosoldable PE',
                                 'Tomada eletrossoldável PE', 'PE-Elektroschweiß-Anbohrarmatur'),
    'Collier seul (sans robinet)': ('Clamp only (no valve)', 'Solo collarín (sin llave)',
                                    'Só braçadeira (sem válvula)', 'Nur Schelle (ohne Ventil)'),
    'Collier de prise seul': ('Tapping clamp only', 'Solo collarín de toma', 'Só braçadeira de tomada',
                              'Nur Anbohrschelle'),
    'Tête carrée (sous bouche à clé)': ('Square head (under valve box)', 'Cabeza cuadrada (bajo arqueta de llave)',
                                        'Cabeça quadrada (sob caixa de manobra)', 'Vierkant (unter Straßenkappe)'),
    'Tête carrée': ('Square head', 'Cabeza cuadrada', 'Cabeça quadrada', 'Vierkant'),
    'Quart de tour': ('Quarter-turn', 'Cuarto de vuelta', 'Quarto de volta', 'Vierteldrehung'),
    'Avant compteur (quart de tour)': ('Before meter (quarter-turn)', 'Antes del contador (cuarto de vuelta)',
                                       'Antes do contador (quarto de volta)', 'Vor dem Zähler (Vierteldrehung)'),
    'Après compteur (avec purge)': ('After meter (with drain)', 'Después del contador (con purga)',
                                    'Depois do contador (com purga)', 'Nach dem Zähler (mit Entleerung)'),
    'Robinet avant compteur': ('Valve before meter', 'Llave antes del contador', 'Válvula antes do contador',
                               'Ventil vor dem Zähler'),
    'Robinet après compteur': ('Valve after meter', 'Llave después del contador', 'Válvula depois do contador',
                               'Ventil nach dem Zähler'),
    'Robinet de purge': ('Drain valve', 'Llave de purga', 'Válvula de purga', 'Entleerungsventil'),
    'avant compteur': ('before meter', 'antes del contador', 'antes do contador', 'vor dem Zähler'),
    'après compteur': ('after meter', 'después del contador', 'depois do contador', 'nach dem Zähler'),
    'de purge': ('drain', 'de purga', 'de purga', 'Entleerung'),
    'd’isolement': ('isolating', 'de aislamiento', 'de isolamento', 'Absperrung'),
    'Purge / vidange': ('Drain / purge', 'Purga / vaciado', 'Purga / descarga', 'Entleerung'),
    'Isolement': ('Isolation', 'Aislamiento', 'Isolamento', 'Absperrung'),
    'Volumétrique': ('Volumetric', 'Volumétrico', 'Volumétrico', 'Volumenzähler'),
    'Vitesse (jet unique)': ('Velocity (single jet)', 'Velocidad (chorro único)', 'Velocidade (jato único)',
                             'Flügelrad (Einstrahl)'),
    'Vitesse jet unique': ('Single-jet velocity', 'Velocidad chorro único', 'Velocidade jato único',
                           'Einstrahl-Flügelrad'),
    'Électromagnétique / ultrasons': ('Electromagnetic / ultrasonic', 'Electromagnético / ultrasonidos',
                                      'Eletromagnético / ultrassons', 'Magnetisch-induktiv / Ultraschall'),
    'Électromagnétique': ('Electromagnetic', 'Electromagnético', 'Eletromagnético', 'Magnetisch-induktiv'),
    'Aucun': ('None', 'Ninguno', 'Nenhum', 'Keiner'),
    'Regard de comptage': ('Meter pit', 'Arqueta de contador', 'Caixa de contador', 'Zählerschacht'),
    'Abri / citerneau incongelable': ('Frost-proof meter box', 'Armario de contador antihielo',
                                      'Caixa de contador anticongelante', 'Frostsicherer Zählerschacht'),
    'Abri de compteur incongelable': ('Frost-proof meter box', 'Armario de contador antihielo',
                                      'Caixa de contador anticongelante', 'Frostsicherer Zählerschacht'),
    'Niche en façade': ('Wall niche', 'Hornacina en fachada', 'Nicho na fachada', 'Fassadennische'),
    'Niche de comptage en façade': ('Wall meter niche', 'Hornacina de contador en fachada',
                                    'Nicho de contador na fachada', 'Zählernische in der Fassade'),
    'Local technique': ('Plant room', 'Local técnico', 'Local técnico', 'Technikraum'),
    'Incongelable': ('Frost-proof', 'Antihielo', 'Anticongelante', 'Frostsicher'),
    'Renversable': ('Breakaway', 'Abatible', 'Rebatível', 'Mit Sollbruchstelle'),
    'À prises apparentes': ('With exposed outlets', 'Con tomas vistas', 'Com tomadas à vista',
                            'Mit sichtbaren Abgängen'),
    'Bouche d’arrosage': ('Irrigation hydrant', 'Boca de riego', 'Boca de rega', 'Bewässerungshydrant'),
    'Bouche de lavage': ('Street washing hydrant', 'Boca de limpieza', 'Boca de lavagem', 'Spülhydrant'),
    'Prise d’eau de voirie': ('Road water point', 'Toma de agua de vía pública', 'Tomada de água de via pública',
                              'Straßenzapfstelle'),
    'Semi-enterré': ('Semi-buried', 'Semienterrado', 'Semienterrado', 'Halb erdverlegt'),
    'Enterré': ('Buried', 'Enterrado', 'Enterrado', 'Erdverlegt'),
    'Château d’eau': ('Water tower', 'Depósito elevado', 'Reservatório elevado', 'Wasserturm'),
    'Surélevé – point géodésique': ('Elevated – survey point', 'Elevado – punto geodésico',
                                    'Elevado – ponto geodésico', 'Hochbehälter – Festpunkt'),
    'Bâche de reprise': ('Break tank', 'Depósito de rebombeo', 'Reservatório de rebombagem', 'Zwischenbehälter'),
    'Réservoir semi-enterré': ('Semi-buried reservoir', 'Depósito semienterrado', 'Reservatório semienterrado',
                               'Halb erdverlegter Behälter'),
    'Réservoir enterré': ('Buried reservoir', 'Depósito enterrado', 'Reservatório enterrado',
                          'Erdverlegter Behälter'),
    'Réservoir surélevé (point géodésique)': ('Elevated reservoir (survey point)',
                                              'Depósito elevado (punto geodésico)',
                                              'Reservatório elevado (ponto geodésico)', 'Hochbehälter (Festpunkt)'),
    'Pompe de refoulement': ('Delivery pump', 'Bomba de impulsión', 'Bomba elevatória', 'Förderpumpe'),
    'Surpresseur': ('Booster', 'Grupo de presión', 'Sobrepressor', 'Druckerhöhungsanlage'),
    'Pompe immergée (forage)': ('Submersible pump (borehole)', 'Bomba sumergible (pozo)',
                                'Bomba submersível (furo)', 'Unterwasserpumpe (Brunnen)'),
    'Pompe immergée': ('Submersible pump', 'Bomba sumergible', 'Bomba submersível', 'Unterwasserpumpe'),
    'Puits, forage': ('Well, borehole', 'Pozo, sondeo', 'Poço, furo', 'Brunnen, Bohrung'),
    'Puits / forage': ('Well / borehole', 'Pozo / sondeo', 'Poço / furo', 'Brunnen / Bohrung'),
    'Source (captage)': ('Spring (intake)', 'Manantial (captación)', 'Nascente (captação)', 'Quelle (Fassung)'),
    'Prise d’eau superficielle': ('Surface water intake', 'Toma de agua superficial',
                                  'Captação de água superficial', 'Oberflächenwasserentnahme'),
    'Chloration (hypochlorite)': ('Chlorination (hypochlorite)', 'Cloración (hipoclorito)',
                                  'Cloragem (hipoclorito)', 'Chlorung (Hypochlorit)'),
    'Chloration gazeuse': ('Gas chlorination', 'Cloración gaseosa', 'Cloragem gasosa', 'Gaschlorung'),
    'Désinfection UV': ('UV disinfection', 'Desinfección UV', 'Desinfeção UV', 'UV-Desinfektion'),
    'Filtration': ('Filtration', 'Filtración', 'Filtração', 'Filtration'),
    'Reminéralisation': ('Remineralisation', 'Remineralización', 'Remineralização', 'Aufhärtung'),
    'Réduction + stabilisation': ('Reducing + sustaining', 'Reducción + sostenimiento',
                                  'Redução + estabilização', 'Druckminderung + Druckhaltung'),
    'Chambre de vannes': ('Valve chamber', 'Cámara de válvulas', 'Câmara de válvulas', 'Schieberkammer'),
    'Note': ('Note', 'Nota', 'Nota', 'Notiz'),

    # ── Pièces ──────────────────────────────────────────────────────────
    'Tuyau': ('Pipe', 'Tubo', 'Tubo', 'Rohr'),
    'Coude': ('Bend', 'Codo', 'Curva', 'Bogen'),
    'Coude à patin (pied d’assise)': ('Duckfoot bend (base bend)', 'Codo con patín (pie de apoyo)',
                                      'Curva com patim (pé de apoio)', 'Fußkrümmer (N-Stück)'),
    'Coude à patin': ('Duckfoot bend', 'Codo con patín', 'Curva com patim', 'Fußkrümmer'),
    'Té': ('Tee', 'Te', 'Tê', 'T-Stück'),
    'Croix à brides': ('Flanged cross', 'Cruz con bridas', 'Cruzeta flangeada', 'Flansch-Kreuzstück'),
    'Croix': ('Cross', 'Cruz', 'Cruzeta', 'Kreuzstück'),
    'Cône de réduction': ('Reducer', 'Cono de reducción', 'Cone de redução', 'Übergangsstück'),
    'Cône': ('Reducer', 'Cono', 'Cone', 'Übergangsstück'),
    'Manchon': ('Coupling', 'Manguito', 'Manga', 'Muffe'),
    'Bride-emboîtement (BE)': ('Flange-socket (BE)', 'Brida-enchufe (BE)', 'Flange-boca (BE)',
                               'Flansch-Muffen-Stück (BE)'),
    'Bride-bout uni (BU)': ('Flange-spigot (BU)', 'Brida-extremo liso (BU)', 'Flange-ponta lisa (BU)',
                            'Flansch-Spitzende-Stück (BU)'),
    'Adaptateur de bride multi-matériaux': ('Multi-material flange adaptor', 'Adaptador de brida multimaterial',
                                            'Adaptador de flange multimaterial', 'Mehrwerkstoff-Flanschadapter'),
    'Raccord universel multi-matériaux': ('Multi-material universal coupling', 'Racor universal multimaterial',
                                          'União universal multimaterial', 'Mehrwerkstoff-Universalkupplung'),
    'Manchette à brides': ('Flanged spool', 'Carrete con bridas', 'Carretel flangeado', 'Flansch-Passstück'),
    'Manchette': ('Spool', 'Carrete', 'Carretel', 'Passstück'),
    'Plaque (bride) de réduction': ('Reducing (flange) plate', 'Placa (brida) de reducción',
                                    'Placa (flange) de redução', 'Reduzierflansch'),
    'Collet PE + bride tournante': ('PE stub end + backing flange', 'Portabridas PE + brida loca',
                                    'Colarinho PE + flange louca', 'PE-Bund + Losflansch'),
    'Bouchon / obturateur': ('Cap / plug', 'Tapón / obturador', 'Tampão / obturador', 'Kappe / Stopfen'),
    'Bouchon': ('Cap', 'Tapón', 'Tampão', 'Kappe'),
    'Plaque pleine (bride pleine)': ('Blank flange', 'Brida ciega', 'Flange cega', 'Blindflansch'),
    'Plaque pleine': ('Blank flange', 'Brida ciega', 'Flange cega', 'Blindflansch'),
    'Manchon à compression': ('Compression coupling', 'Manguito de compresión', 'União de compressão',
                              'Klemmmuffe'),
    'Coude à compression 90°': ('90° compression elbow', 'Codo de compresión 90°', 'Curva de compressão 90°',
                                'Klemmwinkel 90°'),
    'Coude 90° à compression PE': ('90° PE compression elbow', 'Codo 90° de compresión PE',
                                   'Curva 90° de compressão PE', 'PE-Klemmwinkel 90°'),
    'Té à compression': ('Compression tee', 'Te de compresión', 'Tê de compressão', 'Klemm-T-Stück'),
    'Raccord compression / fileté mâle': ('Compression / male thread adaptor', 'Racor compresión / rosca macho',
                                          'União compressão / rosca macho', 'Klemmverbinder / Außengewinde'),
    'Raccord compression / fileté femelle': ('Compression / female thread adaptor',
                                             'Racor compresión / rosca hembra', 'União compressão / rosca fêmea',
                                             'Klemmverbinder / Innengewinde'),
    'Raccord compression PE': ('PE compression adaptor', 'Racor compresión PE', 'União compressão PE',
                               'PE-Klemmverbinder'),
    'fileté mâle': ('male thread', 'rosca macho', 'rosca macho', 'Außengewinde'),
    'fileté femelle': ('female thread', 'rosca hembra', 'rosca fêmea', 'Innengewinde'),
    'Bouchon à compression': ('Compression cap', 'Tapón de compresión', 'Tampão de compressão', 'Klemmkappe'),
    'Mamelon double (M-M)': ('Double nipple (M-M)', 'Niple doble (M-M)', 'Casquilho duplo (M-M)',
                             'Doppelnippel (AG-AG)'),
    'Mamelon double': ('Double nipple', 'Niple doble', 'Casquilho duplo', 'Doppelnippel'),
    'Mamelon': ('Nipple', 'Niple', 'Casquilho', 'Nippel'),
    'Manchon fileté (F-F)': ('Threaded socket (F-F)', 'Manguito roscado (H-H)', 'Manga roscada (F-F)',
                             'Gewindemuffe (IG-IG)'),
    'Manchon fileté': ('Threaded socket', 'Manguito roscado', 'Manga roscada', 'Gewindemuffe'),
    'Réduction filetée (M-F)': ('Threaded reducer (M-F)', 'Reducción roscada (M-H)', 'Redução roscada (M-F)',
                                'Gewindereduzierung (AG-IG)'),
    'Réduction filetée': ('Threaded reducer', 'Reducción roscada', 'Redução roscada', 'Gewindereduzierung'),
    'Réd.': ('Red.', 'Red.', 'Red.', 'Red.'),
    'Robinet-vanne (opercule)': ('Gate valve', 'Válvula de compuerta', 'Válvula de cunha', 'Absperrschieber'),
    'Robinet-vanne à opercule': ('Gate valve', 'Válvula de compuerta', 'Válvula de cunha', 'Absperrschieber'),
    'Robinet-vanne de vidange': ('Drain gate valve', 'Válvula de compuerta de vaciado',
                                 'Válvula de cunha de descarga', 'Entleerungsschieber'),
    'Vanne papillon': ('Butterfly valve', 'Válvula de mariposa', 'Válvula de borboleta', 'Absperrklappe'),
    'Robinet ¼ de tour': ('¼-turn valve', 'Llave de ¼ de vuelta', 'Válvula de ¼ de volta', '¼-Drehventil'),
    'Clapet anti-retour contrôlable (EA)': ('Testable non-return valve (EA)',
                                            'Válvula antirretorno controlable (EA)',
                                            'Válvula antirretorno controlável (EA)',
                                            'Prüfbarer Rückflussverhinderer (EA)'),
    'Clapet anti-retour': ('Non-return valve', 'Válvula antirretorno', 'Válvula antirretorno', 'Rückschlagventil'),
    'Filtre à tamis': ('Strainer', 'Filtro de tamiz', 'Filtro de rede', 'Schmutzfänger'),
    'Filtre': ('Strainer', 'Filtro', 'Filtro', 'Schmutzfänger'),
    'Réducteur de pression': ('Pressure reducing valve', 'Reductor de presión', 'Redutor de pressão',
                              'Druckminderer'),
    'Stabilisateur amont': ('Pressure sustaining valve', 'Sostenedor de presión', 'Estabilizador a montante',
                            'Druckhalteventil'),
    'Stabilisateur de pression amont': ('Upstream pressure sustaining valve',
                                        'Sostenedor de presión aguas arriba',
                                        'Estabilizador de pressão a montante', 'Druckhalteventil'),
    'Régulateur / limiteur de débit': ('Flow control / limiting valve', 'Regulador / limitador de caudal',
                                       'Regulador / limitador de caudal', 'Durchflussregler / -begrenzer'),
    'Régulateur de débit': ('Flow regulator', 'Regulador de caudal', 'Regulador de caudal', 'Durchflussregler'),
    'Vanne de régulation hydraulique': ('Hydraulic control valve', 'Válvula de regulación hidráulica',
                                        'Válvula de regulação hidráulica', 'Hydraulisches Regelventil'),
    'Vanne altimétrique': ('Altitude valve', 'Válvula de altitud', 'Válvula altimétrica', 'Höhenstandsventil'),
    'Ventouse': ('Air valve', 'Ventosa', 'Ventosa', 'Be- und Entlüfter'),
    'Robinet d’isolement de ventouse': ('Air valve isolating valve', 'Válvula de aislamiento de ventosa',
                                        'Válvula de isolamento de ventosa', 'Absperrventil für Be- und Entlüfter'),
    'Vidange / purge de réseau': ('Network drain / washout', 'Vaciado / purga de red',
                                  'Descarga / purga de rede', 'Netzentleerung'),
    'Vidange': ('Drain', 'Vaciado', 'Descarga', 'Entleerung'),
    'Conduite de vidange': ('Drain pipe', 'Tubería de vaciado', 'Conduta de descarga', 'Entleerungsleitung'),
    'Conduite de purge': ('Drain pipe', 'Tubería de purga', 'Conduta de purga', 'Entleerungsleitung'),
    'Purge': ('Drain', 'Purga', 'Purga', 'Entleerung'),
    'Soupape de décharge': ('Pressure relief valve', 'Válvula de alivio', 'Válvula de alívio',
                            'Sicherheitsventil'),
    'Réservoir anti-bélier': ('Surge vessel', 'Calderín antiariete', 'Reservatório anti-golpe de aríete',
                              'Druckstoßbehälter'),
    'Anti-bélier': ('Surge vessel', 'Antiariete', 'Anti-golpe de aríete', 'Druckstoßbehälter'),
    'Robinet à flotteur': ('Float valve', 'Válvula de flotador', 'Válvula de boia', 'Schwimmerventil'),
    'Flotteur': ('Float valve', 'Flotador', 'Boia', 'Schwimmerventil'),
    'Robinet de prise en charge': ('Tapping valve', 'Llave de toma en carga', 'Válvula de tomada em carga',
                                   'Anbohrventil'),
    'Collier de prise en charge': ('Tapping saddle', 'Collarín de toma en carga',
                                   'Braçadeira de tomada em carga', 'Anbohrschelle'),
    'Robinet d’arrêt de branchement': ('Service stop valve', 'Llave de corte de acometida',
                                       'Válvula de corte do ramal', 'Hausanschluss-Absperrventil'),
    'Robinet à boisseau sphérique': ('Ball valve', 'Válvula de bola', 'Válvula de esfera', 'Kugelhahn'),
    'à boisseau sphérique': ('ball valve', 'de bola', 'de esfera', 'Kugelhahn'),
    'Robinet': ('Valve', 'Llave', 'Válvula', 'Ventil'),
    'Compteur d’eau': ('Water meter', 'Contador de agua', 'Contador de água', 'Wasserzähler'),
    'Compteur': ('Meter', 'Contador', 'Contador', 'Zähler'),
    'Tête émettrice de télérelève': ('Remote-reading transmitter', 'Emisor de telelectura',
                                     'Emissor de telecontagem', 'Funkmodul für Fernauslesung'),
    'Disconnecteur BA': ('BA backflow preventer', 'Desconector BA', 'Desconector BA', 'Systemtrenner BA'),
    'Disconnecteur à zone de pression réduite contrôlable (BA)': (
        'Testable reduced pressure zone backflow preventer (BA)',
        'Desconector de zona de presión reducida controlable (BA)',
        'Desconector de zona de pressão reduzida controlável (BA)',
        'Systemtrenner mit kontrollierbarer Mitteldruckzone (BA)'),
    'Débitmètre électromagnétique': ('Electromagnetic flowmeter', 'Caudalímetro electromagnético',
                                     'Caudalímetro eletromagnético', 'Magnetisch-induktiver Durchflussmesser'),
    'Poteau d’incendie': ('Pillar fire hydrant', 'Hidrante de columna', 'Marco de incêndio', 'Überflurhydrant'),
    'Bouche d’incendie': ('Underground fire hydrant', 'Hidrante enterrado', 'Boca de incêndio',
                          'Unterflurhydrant'),
    'Bouche d’arrosage / de lavage': ('Irrigation / washing hydrant', 'Boca de riego / limpieza',
                                      'Boca de rega / lavagem', 'Bewässerungs- / Spülhydrant'),
    'Borne fontaine': ('Drinking fountain', 'Fuente pública', 'Fontanário', 'Trinkbrunnen'),
    'Borne de puisage': ('Standpipe', 'Punto de toma de agua', 'Marco de abastecimento', 'Zapfstelle'),
    'Borne puisage': ('Standpipe', 'Punto de toma', 'Marco de abastecimento', 'Zapfstelle'),
    'Pièce de réglage (en S)': ('Adjusting piece (S-shaped)', 'Pieza de ajuste (en S)', 'Peça de ajuste (em S)',
                                'Passstück (S-Form)'),
    'Pièce de réglage': ('Adjusting piece', 'Pieza de ajuste', 'Peça de ajuste', 'Passstück'),
    'Abonné / installation privée': ('Customer / private installation', 'Abonado / instalación privada',
                                     'Cliente / instalação privada', 'Kunde / Hausinstallation'),
    'Abonné': ('Customer', 'Abonado', 'Cliente', 'Kunde'),
    'Réseau existant (raccordement)': ('Existing network (connection)', 'Red existente (conexión)',
                                       'Rede existente (ligação)', 'Bestehendes Netz (Anschluss)'),
    'Existant': ('Existing', 'Existente', 'Existente', 'Bestand'),
    'Réservoir / château d’eau': ('Reservoir / water tower', 'Depósito / depósito elevado',
                                  'Reservatório / reservatório elevado', 'Behälter / Wasserturm'),
    'Pompe / surpresseur': ('Pump / booster', 'Bomba / grupo de presión', 'Bomba / sobrepressor',
                            'Pumpe / Druckerhöhung'),
    'Pompe': ('Pump', 'Bomba', 'Bomba', 'Pumpe'),
    'Captage (source, puits, forage, prise d’eau)': ('Intake (spring, well, borehole, water intake)',
                                                     'Captación (manantial, pozo, sondeo, toma)',
                                                     'Captação (nascente, poço, furo, tomada)',
                                                     'Fassung (Quelle, Brunnen, Bohrung, Entnahme)'),
    'Forage': ('Borehole', 'Sondeo', 'Furo', 'Bohrung'),
    'Tête de forage / captage': ('Borehole / intake head', 'Cabeza de sondeo / captación',
                                 'Cabeça de furo / captação', 'Brunnenkopf / Fassung'),
    'ouvrage de captage': ('intake structure', 'obra de captación', 'obra de captação', 'Fassungsbauwerk'),
    'Poste de traitement': ('Treatment unit', 'Estación de tratamiento', 'Posto de tratamento',
                            'Aufbereitungsanlage'),
    'Traitement': ('Treatment', 'Tratamiento', 'Tratamento', 'Aufbereitung'),
    'Regard / chambre (cadre)': ('Chamber (frame)', 'Arqueta / cámara (marco)', 'Caixa / câmara (quadro)',
                                 'Schacht / Kammer (Rahmen)'),
    'Regard / chambre': ('Chamber', 'Arqueta / cámara', 'Caixa / câmara', 'Schacht / Kammer'),
    'Texte / note': ('Text / note', 'Texto / nota', 'Texto / nota', 'Text / Notiz'),

    # ── Morceaux de nomenclature et d'étiquettes ────────────────────────
    'Grillage avertisseur bleu': ('Blue warning mesh', 'Malla de señalización azul', 'Rede de sinalização azul',
                                  'Blaues Trassenwarnband'),
    'Fourreau pour': ('Sleeve for', 'Funda para', 'Manga para', 'Schutzrohr für'),
    'verrouillé': ('restrained', 'acerrojado', 'travado', 'längskraftschlüssig'),
    'auto-buté': ('self-restrained', 'autoblocante', 'autotravado', 'selbstsichernd'),
    'Adapt. bride': ('Flange adapt.', 'Adapt. brida', 'Adapt. flange', 'Flanschadapt.'),
    'Adaptateur de bride grande tolérance': ('Wide-tolerance flange adaptor',
                                             'Adaptador de brida de gran tolerancia',
                                             'Adaptador de flange de grande tolerância',
                                             'Flanschadapter mit großem Toleranzbereich'),
    'Raccord univ.': ('Univ. coupling', 'Racor univ.', 'União univ.', 'Universalkuppl.'),
    'Raccord universel grande tolérance': ('Wide-tolerance universal coupling',
                                           'Racor universal de gran tolerancia',
                                           'União universal de grande tolerância',
                                           'Universalkupplung mit großem Toleranzbereich'),
    'anc.': ('anch.', 'anc.', 'anc.', 'Anker'),
    'Bride de réduction': ('Reducing flange', 'Brida de reducción', 'Flange de redução', 'Reduzierflansch'),
    'Bride réd.': ('Red. flange', 'Brida red.', 'Flange red.', 'Red.-Flansch'),
    'Collet PE': ('PE stub end', 'Portabridas PE', 'Colarinho PE', 'PE-Bund'),
    'Collet': ('Stub end', 'Portabridas', 'Colarinho', 'Bund'),
    'bride tournante': ('backing flange', 'brida loca', 'flange louca', 'Losflansch'),
    'Collier rép.': ('Rep. clamp', 'Abraz. rep.', 'Braç. rep.', 'Rep.-Schelle'),
    'sortie PE': ('PE outlet', 'salida PE', 'saída PE', 'PE-Abgang'),
    'réduit': ('reduced', 'reducido', 'reduzido', 'reduziert'),
    'consigne aval': ('downstream setpoint', 'consigna aguas abajo', 'consigna a jusante', 'Ausgangsdruck'),
    'consigne': ('setpoint', 'consigna', 'consigna', 'Sollwert'),
    'tarage': ('set pressure', 'tarado', 'calibração', 'Ansprechdruck'),
    'profondeur': ('depth', 'profundidad', 'profundidade', 'Tiefe'),
    'm HMT': ('m TDH', 'm AMT', 'm AMT', 'm Förderhöhe'),
    'sur': ('on', 'sobre', 'sobre', 'auf'),
    'vers': ('to', 'hacia', 'para', 'nach'),
    'à': ('at', 'a', 'a', 'bei'),
    'Bouche à clé + tube allonge + tige de manœuvre': ('Valve box + extension tube + operating stem',
                                                       'Arqueta de llave + tubo prolongador + vástago de maniobra',
                                                       'Caixa de manobra + tubo prolongador + haste de manobra',
                                                       'Straßenkappe + Verlängerungsrohr + Einbaugarnitur'),
    'Regard de visite pour appareil': ('Access chamber for fitting', 'Arqueta de registro para aparato',
                                       'Caixa de visita para aparelho', 'Armaturenschacht'),
    'Désignation;Quantité;Unité': ('Description;Quantity;Unit', 'Designación;Cantidad;Unidad',
                                   'Designação;Quantidade;Unidade', 'Bezeichnung;Menge;Einheit'),

    # ── Messages de contrôle ────────────────────────────────────────────
    'assemblage impossible': ('joint impossible', 'unión imposible', 'ligação impossível',
                              'Verbindung nicht möglich'),
    'pièces non alignées': ('fittings not aligned', 'piezas no alineadas', 'peças não alinhadas',
                            'Formstücke nicht fluchtend'),
    'bride de réduction ou cône': ('reducing flange or reducer', 'brida de reducción o cono',
                                   'flange de redução ou cone', 'Reduzierflansch oder Übergangsstück'),
    'matériaux différents': ('different materials', 'materiales diferentes', 'materiais diferentes',
                             'unterschiedliche Werkstoffe'),
    'raccord universel / adaptateur': ('universal coupling / adaptor', 'racor universal / adaptador',
                                       'união universal / adaptador', 'Universalkupplung / Adapter'),
    'diamètres différents': ('different diameters', 'diámetros diferentes', 'diâmetros diferentes',
                             'unterschiedliche Durchmesser'),
    'cône / réduction': ('reducer', 'cono / reducción', 'cone / redução', 'Übergangsstück / Reduzierung'),
    'Pas de joints verrouillés sur cette pièce : emboîtement simple.': (
        'No restrained joints on this fitting: plain socket.',
        'Sin juntas acerrojadas en esta pieza: enchufe simple.',
        'Sem juntas travadas nesta peça: boca simples.',
        'Keine längskraftschlüssigen Verbindungen an diesem Formstück: einfache Muffe.'),
    'format inconnu': ('unknown format', 'formato desconocido', 'formato desconhecido', 'unbekanntes Format'),

    # ── Montages livrés ─────────────────────────────────────────────────
    'Branchement sur prise en charge (détaillé)': ('Service connection on tapping (detailed)',
                                                   'Acometida en toma en carga (detallada)',
                                                   'Ramal em tomada em carga (detalhado)',
                                                   'Hausanschluss mit Anbohrung (detailliert)'),
    'Branchement sur prise en charge': ('Service connection on tapping', 'Acometida en toma en carga',
                                        'Ramal em tomada em carga', 'Hausanschluss mit Anbohrung'),
    'Vanne': ('Valve', 'Válvula', 'Válvula', 'Schieber'),
}

# Unités de nomenclature : u (unité), ml (mètre linéaire), ens (ensemble).
UNITES = {
    'u': ('pc', 'ud', 'un', 'St'),
    'ml': ('m', 'm', 'm', 'm'),
    'ens': ('set', 'conj.', 'conj.', 'Satz'),
}
